# This workflow creates all environment-specific resources that are shared across applications.
# This needs to run before creating an application-specific environment.
name: 02 - Manually create a shared environment

permissions:
  id-token: write
  contents: read

env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}

on:
  workflow_dispatch:
    inputs:
      environmentName:
        description: 'The name of the environment to create.'
        required: true
        default: 'staging'
jobs:
  deploy-network-stack:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Deploy the network stack
    steps:

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: GitHubActions-Backend-${{ github.run_id }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Make mvnw executable
        run: chmod +x ./cdk/mvnw

      - name: NPM install
        working-directory: cdk
        run: npm install

      - name: Deploy network stack
        working-directory: cdk
        run: npm run network:deploy -- -c environmentName=${{ github.event.inputs.environmentName }}
